name: depup
on:
  schedule:
    - cron:  '14 14 * * *'
  workflow_dispatch:
  push: # for testing
    branches:
      - '**'

jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./with-pr
        with:
          file: testdata/testfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

  redpen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./with-pr
        with:
          file: testdata/testfile
          version_name: REDPEN_VERSION
          repo: redpen-cc/redpen
          tag_prefix: redpen-

  themis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./with-pr
        id: depup
        with:
          file: testdata/testfile
          version_name: THEMIS_VERSION
          repo: thinca/vim-themis
          tag: true
