name: Test
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Check diff
        run: git diff

  needless_prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: REDPEN_VERSION
          repo: redpen-cc/redpen

      - name: Check diff
        run: git diff

  not_semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: TMUX_VERSION
          repo: tmux/tmux

      - name: Check diff
        run: git diff

  quoted_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: POETRY_VERSION
          repo: python-poetry/poetry

      - name: Check diff
        run: git diff

  tagged_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: THEMIS_VERSION
          repo: thinca/vim-themis
          tag: true

      - name: Check diff
        run: git diff
