name: Test
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: REVIEWDOG_VERSION
          repo: reviewdog/reviewdog

      - name: Check diff
        run: git diff

  needless_prefix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: REDPEN_VERSION
          repo: redpen-cc/redpen

      - name: Check diff
        run: git diff

  not_semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: depup
        with:
          file: testdata/testfile
          version_name: TMUX_VERSION
          repo: tmux/tmux

      - name: Check diff
        run: git diff
